version: '3.9'

services:
  postgres-database:
    image: postgres:13
    container_name: bank-api-database
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
